# Generated by Django 4.2.2 on 2023-07-03 06:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of type product', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The product name', max_length=50)),
                ('description', models.TextField(help_text='Product description', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True)),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.producttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
