# Generated by Django 4.2.2 on 2023-07-03 06:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeSumm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of type product', max_length=50)),
                ('sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_type_summ',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW product_type_summ AS 
                SELECT 
                pt.id, 
                pt.name, 
                SUM(p.price) 
                FROM lesson_producttype pt 
                LEFT JOIN lesson_product p 
                ON pt.id=p.product_type_id 
                GROUP BY pt.id;
            """,
            "DROP VIEW product_type_summ;"
        )
    ]
